media:
  input: media
  output: /_site/media
components:
  image:
    type: object
    label: Image
    fields:
      - name: image
        label: Image
        type: image
        media: media
        rename: safe
      - name: title
        label: Title
        description: The title of this specific image.
        type: string
      - name: description
        label: Description
        description: The description for this specific image.
        type: rich-text
content:
  - name: global
    label: Global values
    type: file
    path: content/_data/global.json
    fields:
      - name: bio
        label: Bio
        type: rich-text
        description: A little about yourself
        options:
          format: html
          media: media
  - name: portfolio
    label: Portfolio
    type: collection
    filename: "{primary}.md"
    path: content/portfolio
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm
      - name: images
        label: Images
        description: Images for this entry, best one first.
        component: image
        list: true
      - name: references
        label: References
        description: References for this entry, if any.
        component: image
        list: true
      - name: body
        label: Body
        description: A description for this entry, or just write whatever.
        type: rich-text
      - name: tags
        label: Tags
        description: Categories for this entry.
        type: string
        list: true
